### ISSUE TITLE
Dataset seems down

### ISSUE THREAD

**Issue by Tobias-Fischer** [AutonomyLab/sfu-mountain-dataset#1]
Hi @jakebruce,
I hope you're doing well!

It seems that the files linked from http://autonomy.cs.sfu.ca/sfu-mountain-dataset/ are down. Do you have a mirror somewhere? We're particularly interested in the place match files.

Thanks, Tobi

**Comment by jakebruce** [comment]
Hi Tobi!

Sorry about the inconvenience and thanks for bringing this to my attention! This data is hosted by a legacy system at one of my previous institutions, I've reached out to a more recent maintainer to see what we can do.

Cheers,
Jake
________________________________
From: Tobias Fischer ***@***.***>
Sent: Sunday, January 9, 2022 11:51:53 PM
To: AutonomyLab/sfu-mountain-dataset ***@***.***>
Cc: Jake Bruce ***@***.***>; Mention ***@***.***>
Subject: [AutonomyLab/sfu-mountain-dataset] Dataset seems down (Issue #1)


Hi @jakebruce<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjakebruce&data=04%7C01%7C%7Ce4bb2783e43348f4c5b308d9d3cb038e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637773691204810267%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x8R%2FD7Q93Iek2nRpkYdXztIOa9Js%2BFDgL%2Ff32R1dNCY%3D&reserved=0>,
I hope you're doing well!

It seems that the files linked from http://autonomy.cs.sfu.ca/sfu-mountain-dataset/<https://emea01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fautonomy.cs.sfu.ca%2Fsfu-mountain-dataset%2F&data=04%7C01%7C%7Ce4bb2783e43348f4c5b308d9d3cb038e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637773691204820262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rIAucbtRfrc5ESfH6SbQ%2BRT0lowLuh3RNF0Xx%2BME7hE%3D&reserved=0> are down. Do you have a mirror somewhere? We're particularly interested in the place match files.

Thanks, Tobi

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAutonomyLab%2Fsfu-mountain-dataset%2Fissues%2F1&data=04%7C01%7C%7Ce4bb2783e43348f4c5b308d9d3cb038e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637773691204830259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eY0zUV3llA6F7dLuKpu4J%2BT4hIa2T0s%2BlktMP7SRAP0%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA5N25ICOEJO7WT5UFHHYBLUVINRTANCNFSM5LSNYQSQ&data=04%7C01%7C%7Ce4bb2783e43348f4c5b308d9d3cb038e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637773691204830259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=t26PHdmD3wY2XlryU9gy%2FdC3YF2%2FZpoiSYfmMc7sVJ4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ce4bb2783e43348f4c5b308d9d3cb038e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637773691204840251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8HZNbuoNp7j0DB0NLARHiHBKcoWl7ZPTShqbahrEUlU%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ce4bb2783e43348f4c5b308d9d3cb038e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637773691204840251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x4OUy2%2FyTrROIHyxRoCuzytP8pTqusp4Awt15w5qe60%3D&reserved=0>.

**Comment by Tobias-Fischer** [comment]
Thanks Jake!

**Comment by Tobias-Fischer** [comment]
Any news @jakebruce?

**Comment by jakebruce** [comment]
Hey, sorry for the delay! I had to contact the current maintainers; looks like it's back up now. Let me know if it's still a problem.

Cheers,
Jake
________________________________

**Comment by Tobias-Fischer** [comment]
Thanks, can confirm it's working.
